spring.application.name=ms-gateway
server.port=8080

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.routes[0].id=book
spring.cloud.gateway.routes[0].uri=lb://ms-book
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/libros/**

spring.cloud.gateway.routes[1].id=user
spring.cloud.gateway.routes[1].uri=lb://ms-user
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/usuarios/**

spring.cloud.gateway.routes[2].id=loan
spring.cloud.gateway.routes[2].uri=lb://ms-loan
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/prestamos/**

spring.cloud.gateway.routes[3].id=reservation
spring.cloud.gateway.routes[3].uri=lb://ms-reservation
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/v1/reservas/**

spring.cloud.gateway.routes[4].id=penalty
spring.cloud.gateway.routes[4].uri=lb://ms-penalty
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/v1/multas/**

spring.cloud.gateway.routes[5].id=review
spring.cloud.gateway.routes[5].uri=lb://ms-review
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/v1/reseñas/**

spring.cloud.gateway.routes[6].id=auth
spring.cloud.gateway.routes[6].uri=lb://ms-auth
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/v1/auth/**

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
