spring.application.name=ms-gateway
server.port=8080

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.server.webflux.routes[0].id=book
spring.cloud.gateway.server.webflux.routes[0].uri=lb://ms-book
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/v1/libros/**

spring.cloud.gateway.server.webflux.routes[1].id=user
spring.cloud.gateway.server.webflux.routes[1].uri=lb://ms-user
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/v1/usuarios/**

spring.cloud.gateway.server.webflux.routes[2].id=loan
spring.cloud.gateway.server.webflux.routes[2].uri=lb://ms-loan
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/v1/prestamos/**

spring.cloud.gateway.server.webflux.routes[3].id=reservation
spring.cloud.gateway.server.webflux.routes[3].uri=lb://ms-reservation
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/v1/reservas/**

spring.cloud.gateway.server.webflux.routes[4].id=penalty
spring.cloud.gateway.server.webflux.routes[4].uri=lb://ms-penalty
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/v1/multas/**

spring.cloud.gateway.server.webflux.routes[5].id=review
spring.cloud.gateway.server.webflux.routes[5].uri=lb://ms-review
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/api/v1/resenas/**

spring.cloud.gateway.server.webflux.routes[6].id=auth
spring.cloud.gateway.server.webflux.routes[6].uri=lb://ms-auth
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/api/v1/auth/**

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

#   swagger:
springdoc.swagger-ui.path=/swagger-ui.html

springdoc.swagger-ui.urls[0].name=1. Libros
springdoc.swagger-ui.urls[0].url=/api/v1/libros/v3/api-docs

springdoc.swagger-ui.urls[1].name=2. Usuarios
springdoc.swagger-ui.urls[1].url=/api/v1/usuarios/v3/api-docs

springdoc.swagger-ui.urls[2].name=3. Prestamos
springdoc.swagger-ui.urls[2].url=/api/v1/prestamos/v3/api-docs

springdoc.swagger-ui.urls[3].name=4. Multas
springdoc.swagger-ui.urls[3].url=/api/v1/multas/v3/api-docs

springdoc.swagger-ui.urls[4].name=5. Resenas
springdoc.swagger-ui.urls[4].url=/api/v1/resenas/v3/api-docs

springdoc.swagger-ui.urls[5].name=6. Reservas
springdoc.swagger-ui.urls[5].url=/api/v1/reservas/v3/api-docs

springdoc.swagger-ui.urls[6].name=7. Seguridad-Auth
springdoc.swagger-ui.urls[6].url=/api/v1/auth/v3/api-docs